name: Deploy to external repo (GitHub Pages)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Deploy to external repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: lucas100601/lucas100601.github.io
          publish_branch: master
          publish_dir: ./build
          user_name: lucas100601
          user_email: lucas100601.corp@gmail.com
